---
name: lint (go)
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          check-latest: true
          go-version-file: 'go.mod'

      - name: Tidy
        # Pin 3rd party action to a specific version as security best-practice.
        # Version used: https://github.com/katexochen/go-tidy-check/releases/tag/v2.0.1
        uses: katexochen/go-tidy-check@427c8c07d3d83ab8d7290cad04ce71c12eab3674

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.9.0
